Refactor Codeception workflow for reusability and automation
Centralize the workflow using a reusable workflow repository and introduce a setup step to dynamically generate a matrix from `composer.json`. Adds scheduled runs and refines branch filters for improved automation and structure.

diff --git a/.github/workflows/codeception.yaml b/.github/workflows/codeception.yaml
--- a/.github/workflows/codeception.yaml
+++ b/.github/workflows/codeception.yaml
@@ -1,51 +1,91 @@
-name: "Codeception Tests"
+name: "Codeception Tests centralised"
+
 on:
+  schedule:
+    - cron: '0 3 * * 1,3,5'
+  workflow_dispatch:
   push:
     branches:
-      - '*'
-      - '**'
+      - "[0-9]+.[0-9]+"
+      - "[0-9]+.x"
+      - "feature-*"
   pull_request:
     types: [opened, synchronize, reopened]
-  workflow_dispatch:
+
+env:
+  PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
+  PRIVATE_REPO: ${{ github.event.repository.private }}
 
 jobs:
-  build:
+  setup-matrix:
     runs-on: ubuntu-latest
-    strategy:
-        matrix:
-            include:
-                - { php-version: 8.3, dependencies: lowest, pimcore_version: "", experimental: false }
-                - { php-version: 8.4, dependencies: highest, pimcore_version: "", experimental: false }
-                - { php-version: 8.4, dependencies: highest, pimcore_version: "12.x-dev as 12.99.9", experimental: true }
+    outputs:
+      php_versions: ${{ steps.parse-php-versions.outputs.php_versions }}
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      private_repo: ${{ env.PRIVATE_REPO }}
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-      - name: Install PHP
-        uses: shivammathur/setup-php@v2
+      - name: Checkout reusable workflow repo
+        uses: actions/checkout@v4
         with:
-          php-version: "${{ matrix.php-version }}"
-          extensions: curl, mbstring, openssl, pdo, pdo_sqlite
-          ini-values: memory_limit=-1, date.timezone='UTC'
-          coverage: xdebug
-          tools: composer:v2
+          repository: pimcore/workflows-collection-public
+          ref: main
+          path: reusable-workflows
 
-      - name: Validate composer.json and composer.lock
-        run: composer validate
-
-      - name: "Update Pimcore version"
-        env:
-            PIMCORE_VERSION: "${{ matrix.pimcore_version }}"
+      - name: Parse PHP versions from composer.json
+        id: parse-php-versions
         run: |
-            if [ ! -z "$PIMCORE_VERSION" ]; then
-                  composer require --no-update pimcore/pimcore:"${PIMCORE_VERSION}"
-            fi  
+          if [ -f composer.json ]; then
+            php_versions=$(jq -r '.require.php' composer.json | grep -oP '\d+\.\d+' | tr '\n' ',' | sed 's/,$//')
+            if [ -z "$php_versions" ]; then
+              echo "No PHP versions found in composer.json"
+              echo "Setting default PHP value"
+              echo "php_versions=default" >> $GITHUB_OUTPUT
+            else
+              echo "php_versions=$php_versions" >> $GITHUB_OUTPUT
+              echo "#### php versions #### : $php_versions"
+            fi
+          else
+            echo "composer.json not found"
+            exit 1
+          fi
 
-      - name: "Install dependencies with Composer"
-        uses: "ramsey/composer-install@v2"
-        with:
-          dependency-versions: "${{ matrix.dependencies }}"
+      - name: Set up matrix
+        id: set-matrix
+        run: |
+          php_versions="${{ steps.parse-php-versions.outputs.php_versions }}"
+          
+          MATRIX_JSON=$(cat reusable-workflows/codeception-tests-configuration/matrix-config.json)
+          
+          IFS=',' read -ra VERSIONS_ARRAY <<< "$php_versions"
+          
+          FILTERED_MATRIX_JSON=$(echo $MATRIX_JSON | jq --arg php_versions "$php_versions" '
+          {
+            matrix: [
+              .configs[] |
+              select(.php_version == $php_versions) |
+              .matrix[]
+            ]
+          }')
+          
+          ENCODED_MATRIX_JSON=$(echo $FILTERED_MATRIX_JSON | jq -c .)
+          
+          echo "matrix=${ENCODED_MATRIX_JSON}" >> $GITHUB_OUTPUT
 
-      - name: Run tests
-        run: php vendor/bin/codecept run
-
+  codeception-tests:
+    needs: setup-matrix
+    strategy:
+      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
+    uses: pimcore/workflows-collection-public/.github/workflows/reusable-codeception-tests-centralized.yaml@main
+    with:
+      APP_ENV: test
+      PIMCORE_TEST: 1
+      PRIVATE_REPO: ${{ needs.setup-matrix.outputs.private_repo}}
+      PHP_VERSION: ${{ matrix.matrix.php-version }}
+      DATABASE: ${{ matrix.matrix.database }}
+      SERVER_VERSION: ${{ matrix.matrix.server_version }}
+      DEPENDENCIES: ${{ matrix.matrix.dependencies }}
+      EXPERIMENTAL: ${{ matrix.matrix.experimental }}
+      PIMCORE_VERSION: ${{ matrix.matrix.pimcore_version }}
